services:
  docxtmpl:
    build: .
    container_name: Templater
    volumes:
      - ./docxtmpl:/app/docxtmpl
    ports:
      - 8080:8080
    environment:
      DOCXTMPL_API_KEY: Foobar
      DOCXTMPL_API_KEY_2: Barfoo
